#!/usr/bin/env bash

url="$1"
name="$2"
dir=$(date +%Y-%m-%d)
path="static/image"

if [ ! -d "$path" ]; then
    echo "Please check your current work dir if it's the shell-blog home."
    exit 1
elif [ ! -d "$path/$dir" ]; then
    mkdir "$path/$dir"
fi

pathname="$path/$dir/$name"
if [[ "$url" == http* ]]; then
    wget -q -O "$pathname" "$url"
else
    cp "$url" "$pathname"
fi

ext=$(file "$pathname" --extension -b | awk -F/ '{print $1}')
mv "$pathname" "$pathname.$ext"

echo "saved $pathname.$ext"
echo "![$name](/$pathname.$ext)"
