name: Posts-CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check if only markdown files exist.
      run: ci/type.sh
    - name: Check and modify filename in the correct date format.
      run: ci/rename.sh
