name: Posts-CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check and modify filename in the correct date format.
      run: ci/rename.sh
